joewalnes/smoothie

smoothie.js

If label size is differ, the position of larger label is not correct.
For example precision:0 minValue:-113 maxValue:0

Fix position, if differ label sizes (issure #59)

---

package.json
smoothie.d.ts

Add types to the package.json file so they can be found when importing it as a module.
Also there was a missing closing comment in the typescript file which prevented it from working.

Add types to package.json and fix bug in smoothie.d.ts

---

smoothie.js

The condition in the ternary operator is true if there's any
reason NOT to use the window.devicePixelRatio. Put the default
in the 'true' arm, and devicePixelRatio in the 'false' condition
where it's useful.
Tested on iOS with Safari's remote debugger, verified that dpr==2.

Fix inverted logic in devicePixelRatio test

---

smoothie.d.ts
smoothie.js

Adds a 'disable' property to hide a TimeSeries from the Chart.
Allows for manual filtering implementations.

Add 'disable' property to TimeSeries for filtering

---

smoothie.js

I have data arriving in realtime, but it already has its own timestamps. I would like to pass in the data's original timestamps to the timeseries, and have the chart show data at the data timestamps instead of at the current browser time. This pr allows for that. The change also allows me to pause my stream of data and to stream it at different speeds.

Add option to use latest data timestamp as current chart time

---

smoothie.js

I noticed that the tooltip was not displaying any values when I turned on the nonRealtimeData option since it was not identifying the chart data's last timestamp correctly. This pr makes sure the tooltip displays the correct value when the nonRealtimeData option is enabled.

Update tooltip to work with the nonRealtimeData option

---

smoothie.js

Even with the min and max y values displayed on the graph, I found it useful to also see intermediate y values above each vertical section divider.

Add option to add y-axis labels above every vertical section divider

---

smoothie.js

I found it useful to be able to see some old data (beyond the canvas end) to examine interesting data points. I can save data by setting maxDataSetLength to a high number. Adding this option allowed me to implement a scroll bar to be able to view older data. I set displayDataFromPercentile to the scrollbar value.
Will display data from given percentile.
Useful for when you want to see data saved by setting maxDataSetLength to a high number.

Add displayDataFromPercentile option

---

builder/index.html
smoothie.js

The existing code for showing intermediate labels is locked to the left side axis and using scientific representation. The suggested code defaults to use the same axis and formatting as the max/min labels, depending on direction, and with an option to allow the intermediate labels to not be on the same axis. As well as a dedicated formatting function like the max/min labels to allow custom formatting if desired.
After realizing the previous code probably was being used with backwards scrolling i guess the option to move the labels to the other axis may not be very usefull, but the defaults provide uniformity now.
Also added the options to the builder to allow users to play with them.
Suggestions are most welcome.

update to Intermediate labels

---

README.md

Hello,
yarn install has been deprecated in favor of yarn add.

Replace yarn install by yarn add

---

smoothie.d.ts
smoothie.js

This PR allows the user to optionally specify a label when adding a series:
var series_1 = new TimeSeries()
smoothie.addTimeSeries(series_1, { tooltipLabel: 'series-1' })
And that label will be displayed along with the numerical value in the tooltip.

Display Series Label in Tooltip

---

smoothie.js

Open the builder and enable _Scroll Backwards_ and _Series fill_ and notice that the fill doesn't render as intended. This pull fixes that bug.

Fixed a bug in "series fill" when using "scroll backwards"

---

smoothie.d.ts
smoothie.js

Sometimes, I need to stack several charts on top of each other, and to display a label for each chart. Due to space constraints, I prefer to show this label directly on the canvas rather than outside. This PR does just that.

Display a short text on the left of the graph.

---

smoothie.js

I am working with smoothie and everything goes well,  the thing is I am using more than 10 charts at the same time, and some dynamic ones, and my DOM is getting bigger and bigger with this  "smoothie-chart-tooltip" div, even if I am not using tooltip, I just added a little validation and is working.

to avoid unnecessary divs in the dom

---

smoothie.js

Re #114, ```append()``` has been modified so that it rejects a point when the time or value is NaN. Previously, points containing NaN could be added, which did not seem to affect operation visibly, but did cause the timeseries to grow without bound when a time of NaN was added. This mod has been tested by forcing append(NaN,<value>), append(<time>,NaN) and append(NaN,NaN) for every genuine data point I add to a timeseries, then checking they no longer appear in the timeseries array.

Filter NaN

---

builder/index.html
smoothie.d.ts
smoothie.js

One-line non-breaking change, which allows us to do things that look like this:

feat: allow setting interpolation per time series

---

smoothie.js

Leaving the bottom one because `updateTooltip` depends on `lastChartTimestamp`, it needs to get updated before `updateTooltip` call.

perf: remove an unnecessary call to `updateTooltip`

---

smoothie.js

WIP because it is based on #130, which I hope will get merged, otherwise I'll rebase.
See commit message for more info.
The effect is noticeable on the example pages.

fix: chart constantly jumping in 1-2 pixel steps

---

smoothie.js

fix: a memory leak appearing when some `timeSeries.disabled === true`

---

smoothie.js

Includes slight behavior changes, see commit messages.
TODO:

perf: improve `render()`, `append()` & `updateTooltip()` performance

---

smoothie.js

and when the user calls `render` manually with a custom `time` argument
TODO:

fix: `this.delay` not being respected with `nonRealtimeData: true`

---

smoothie.js

It would depend on `scrollBackwards` and `fillStyle` being `undefined` or not. Depending on this, it would either continue the line up to the edge of the canvas or leave it at `lastX`. This makes it so that it is always left at `lastX`.
Before:
After:
TODO:

fix: series fill & stroke being inconsistent for last data time < render time

---

smoothie.js

Before:
After:
Closes #57.
This removes the `grid.sharpLines` option.
Base branch is #131, so TODO:

fix: make all lines sharp

---

smoothie.js

express the license in JSDoc format, reorder a line
I Tested it with Webpack + Terser.

chore: make it easier for build tools to preserve the license comment

---

smoothie.js

This doesn't completely get rid of `innerHTML` usage, but at least
now the developer is responsible for `tooltipFormatter` not returning
dangerous HTML if they decide to override it.

fix: potential XSS when `tooltipLabel` or `strokeStyle` are controlled by users
